### PR TITLE
Fix #6008, Add merge strategy for provide option

### LINKED ISSUE #6008: Provide options not merged from mixins
### Version
2.3.4

### Reproduction link
[https://jsfiddle.net/jason_sanjose/00h2moa2/](https://jsfiddle.net/jason_sanjose/00h2moa2/)

### Steps to reproduce
* Define a component A that uses 2 mixins that each define their own `provide` properties, e.g. `foo` and `bar`. 
* Define a component B inside A that uses `inject` to add `foo` and `bar` properties

### What is expected?
Both `foo` and `bar` should be available in component B.

### What is actually happening?
The `provide` defined by the last mixin is the only one available. 

Looks like the standard options merging only accounts for `inject` but not `provide` https://github.com/vuejs/vue/blob/dev/src/core/util/options.js#L185.

---
Update docs if this behavior is expected.

### PR DESCRIPTION
**Pull request by znck**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

File: src/core/util/options.js [hunk 1]
```diff
@@ -183,6 +183,7 @@ strats.watch = function (parentVal: ?Object, childVal: ?Object): ?Object {
 strats.props =
 strats.methods =
 strats.inject =
+strats.provide =
```
Comment (posva) [inline src/core/util/options.js]: This is actually not enough because `provide` can also be a function that returns an object.

I think we should make `data` strategy reusable and use it for `provide`
Other plugins like vuefire will also benefit from this 🙂

Comment (znck) [inline src/core/util/options.js]: 😝 I'd add a failing test first.

**Comment by znck** [comment]
Hey @posva! I guess I didn't miss anything this time.
