### PR TITLE
Special attributes are invalid when using object syntax in v-bind, fix #5881

### LINKED ISSUE #5881: key attribute set by `v-bind="obj"` is ignored by transition-group
### Version
2.3.4

### Reproduction link
[https://codepen.io/Nirazul/pen/RgGRjm](https://codepen.io/Nirazul/pen/RgGRjm)

### Steps to reproduce
1. Click on the trigger button
2. There is only one list visible instead of two

### What is expected?
According to the [documentation](https://vuejs.org/v2/api/#key) I was expecting that I can use the v-bind object notation to set the key attribute.

### What is actually happening?
The list is not rendered when the `key` attribute is not directly present on the element.

---
I'm aware that `key` is a special attribute and that there may be some sort of "hen and egg" problem at work when rendering items in a transition-group.
If the behaviour is intentional, there's maybe some space for improvement in the documentation.

### PR DESCRIPTION
**Pull request by gebilaoxiong**
https://github.com/vuejs/vue/issues/5881

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by gebilaoxiong** [comment]
ah... 

originally I wanted to change `v-bind` in compile-time, but  it will be a  breaken change.

because the attribute `is` need special treatment.

so I try to add a attribute (`is`) in `VNodeData`

can someone help me see to review it?

I will add unit tests tomorrow.

thx.

File: src/core/instance/render-helpers/bind-object-props.js [hunk 1]
```diff
@@ -1,8 +1,11 @@
 /* @flow */
 
 import config from 'core/config'
+import { makeMap } from 'shared/util'
 import { isObject, warn, toObject } from 'core/util/index'
 
+const isSpecialAttributes = makeMap('key,ref,slot,is')
```
Comment (yyx990803) [inline src/core/instance/render-helpers/bind-object-props.js]: There is a similar util [here](https://github.com/vuejs/vue/blob/dev/src/core/instance/state.js#L57-L61)

Let's extract it into `shared/util` as `isReservedAttribute` to avoid duplication.

Comment (yyx990803) [inline src/core/instance/render-helpers/bind-object-props.js]: Also could you add a test case for each of these attributes?

Comment (gebilaoxiong) [inline src/core/instance/render-helpers/bind-object-props.js]: @yyx990803 

sorry,  It was too late yesterday, I will finish after work today

Do not we need to consider `is`?

Comment (yyx990803) [inline src/core/instance/render-helpers/bind-object-props.js]: `is` should be included. I missed it earlier.

**Comment by gebilaoxiong** [comment]
@yyx990803  

the `props` test case is incomplete, I improve it in the code

**Comment by orennitzan** [comment]
I know it's a bit old, but the documentation recommend to add :key='item.someid' but doe to the fact that key is special it doesn't render to the dom. Is the any solution with that?
Thanks.
