### PR TITLE
fix #4872, use context agnostic Function constructor check

### LINKED ISSUE #4872: Server-side: Function type prop’s default function is undefined when rendering server-side
### Vue.js version
2.1.10

### Reproduction Link
https://github.com/shentao/vue-hackernews-2.0

### Steps to reproduce
1) Run the app
```
npm run dev
```

### What is Expected?
`<my-comp></my-comp>` should render to `<div>Default function result: value</div>`

### What is actually happening?
`<my-comp></my-comp>` throws error:
```
Vue warn]: Invalid prop: type check failed for prop "functionProp". Expected Function, got String. 
(found in component <my-comp> at /Users/damiandulisz/code/private/vue-hackernews-2.0/src/MyComp.vue)
Default function result: undefined
[Vue warn]: Error when rendering component <my-comp> at /Users/damiandulisz/code/private/vue-hackernews-2.0/src/MyComp.vue: 
error during render : /top
TypeError: _vm.functionProp is not a function
    at Proxy.render (__vue_ssr_bundle__:1605:48)
    at VueComponent.Vue._render (/Users/damiandulisz/code/private/vue-hackernews-2.0/node_modules/vue/dist/vue.runtime.common.js:2216:22)
    at renderComponent (/Users/damiandulisz/code/private/vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:6078:25)
    at renderNode (/Users/damiandulisz/code/private/vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:6061:7)
    at next (/Users/damiandulisz/code/private/vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:6197:9)
    at next (/Users/damiandulisz/code/private/vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:6189:7)
    at Object.cachedWrite [as write] (/Users/damiandulisz/code/private/vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:36:9)
    at next (/Users/damiandulisz/code/private/vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:6199:17)
    at cachedWrite (/Users/damiandulisz/code/private/vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:36:9)
    at renderNode (/Users/damiandulisz/code/private/vue-hackernews-2.0/node_modules/vue-server-renderer/build.js:6069:7)
```

### PR DESCRIPTION
**Pull request by HerringtonDarkholme**
If the prototype of a function is also a function, we treat it as `Function` constructor.

This check is context independent, so server side can safely extract vue as an external library. And it is not expensive.

Of course it is not silver bullet. Users can pass a value of which the prototype is set to a function. But naughty users can also rewrite `Function` global, so I think this change is at most as bad as current check.

Other counter examples are welcome!

### CODE REVIEW

File: src/core/util/props.js [hunk 1]
```diff
@@ -70,7 +70,8 @@ function getPropDefaultValue (vm: ?Component, prop: PropOptions, key: string): a
     return vm[key]
   }
   // call factory function for non-Function types
-  return typeof def === 'function' && prop.type !== Function
+  // a value is Function if its prototype is function even across different execution context
+  return typeof def === 'function' && (!prop.type || typeof prop.type.prototype !== 'function')
```
Comment (yyx990803) [inline src/core/util/props.js]: Actually we already have the proper check implemented here: https://github.com/vuejs/vue/blob/dev/src/core/util/props.js#L166-L169

So we can just do `getType(prop.type) === 'Function'`

Comment (HerringtonDarkholme) [inline src/core/util/props.js]: Thanks! Didn't notice that!
