### PR TITLE
fix(v-slot): fix scoped slot normalization combined with v-if

### LINKED ISSUE #12102: [2.6.13] Node after v-if node inside named slot is not shown anymore
### Version
2.6.13

### Reproduction link
[https://codesandbox.io/s/recursing-dream-0zdf5?file=/src/App.vue](https://codesandbox.io/s/recursing-dream-0zdf5?file=/src/App.vue)

### Steps to reproduce
```
<template>
  <ComponentWithSlot>
    <template #slot-name>
      <span v-if="false">...</span>
      <span>This is shown in 2.6.12, but not in 2.6.13.</span>
    </template>
  </ComponentWithSlot>
</template>
```

### What is expected?
The text after the `v-if` node should be shown.

### What is actually happening?
It was shown in 2.6.12, but isn't shown in 2.6.13 anymore.

### PR DESCRIPTION
**Pull request by posva**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
Fixes #12102 
Closes #12103

### CODE REVIEW

File: src/core/vdom/helpers/normalize-scoped-slots.js [hunk 1]
```diff
@@ -64,7 +64,7 @@ function normalizeScopedSlot(normalSlots, key, fn) {
     let vnode: VNode = res && res[0]
```
Comment (caugner) [inline src/core/vdom/helpers/normalize-scoped-slots.js:64]: The type annotation suggests that `vnode` is always a `VNode`, but IMO it can also be `undefined`. Otherwise we wouldn't need the `!vnode` check below.

**Review by caugner — APPROVED** [review]
LGTM, even though my concerns regarding the `vnode` variable remain (`res.length == 0` vs `res.length === 1` seems more intuitive to me).

**Comment by caugner** [comment]
@posva Thanks for the fix. Two questions:
1. Shouldn't this PR be added to the 2.6.14 project?
2. Should we expect a 2.6.14 release these days or rather in weeks?

**Comment by posva** [comment]
A new release in days
