### PR TITLE
Fix: nested child elements can not be updated correctly, fix #5618

### LINKED ISSUE #5618: Elements unnecessarily re-created when an above v-for changes.
### Version
2.3.2

### Reproduction link
[https://jsfiddle.net/gazugafan/a8kverza/2/](https://jsfiddle.net/gazugafan/a8kverza/2/)

### Steps to reproduce
Change the inputs marked "Change Me", then add a row. Any inputs following the v-for rows get re-created (and lose their value), while inputs above remain as they are. This only seems to happen when the inputs and v-for element are contained in a parent component's slot.

### What is expected?
All inputs remain unchanged--regardless of what happens to the sibling v-for element.

### What is actually happening?
Any input elements following the v-for are re-created--resetting their value.

### PR DESCRIPTION
**Pull request by gebilaoxiong**
https://github.com/vuejs/vue/issues/5618

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by gebilaoxiong** [comment]
I think e2e shows the error is not what I am causing

**Comment by gebilaoxiong** [comment]
Well, it's an interesting thing to name the title 🤣

**Comment by gebilaoxiong** [comment]
Wait a moment, the test code seems to have some problems

File: src/core/vdom/helpers/normalize-children.js [hunk 1]
```diff
@@ -45,7 +45,9 @@ function normalizeArrayChildren (children: any, nestedIndex?: string): Array<VNo
     last = res[res.length - 1]
     //  nested
     if (Array.isArray(c)) {
-      res.push.apply(res, normalizeArrayChildren(c, `${nestedIndex || ''}_${i}`))
+      // avoid elements to be set key, which created by slot
+      const subNestedIndex = isTrue(c._rendered) ? undefined : `${nestedIndex || ''}_${i}`
```
Comment (pengchongfu) [inline src/core/vdom/helpers/normalize-children.js]: `_renndered` is set when `process.env.NODE_ENV !== 'production'`.

and not only slot, hand-written render functions could have this problem too.

Comment (gebilaoxiong) [inline src/core/vdom/helpers/normalize-children.js]: @pengchongfu 

I did not find any problems in the ` render function`

html:
```html
 <div id="app"></div>
```
javascript: 
``` javascript
var vm = new Vue({
  el: '#app',
  data: {
    count: 1
  },
  render: function (h) {
    var list = []

    for (var i = 0; i < this.count; i++) {
      list.push(h('span', [this.count]))
    }

    return h('div', [
      list,
      h('input', {attrs: { 
        value: 'a',
        type: 'text'
      }})
    ])
  }
})
```
You can input something in the input box,
then modify the value of `count` in the console

and input`s value did not changed

Comment (gebilaoxiong) [inline src/core/vdom/helpers/normalize-children.js]: @pengchongfu 

Can you give me a render example of `hand-written render functions`? 🌹

Comment (pengchongfu) [inline src/core/vdom/helpers/normalize-children.js]: @gebilaoxiong , [demo](https://jsfiddle.net/Lzxnmn9p/), hack... maybe we should ignore it 😂

and `_rendered` is not set in production, see this [line](https://github.com/vuejs/vue/blob/dev/src/core/instance/render-helpers/render-slot.js#L24)

Comment (gebilaoxiong) [inline src/core/vdom/helpers/normalize-children.js]: @pengchongfu 

💋  Thanks , I'll take a look at this question

**Comment by gebilaoxiong** [comment]
@pengchongfu 

Now when using render function does not exist this problem

I'm going to add a test case : )

**Comment by pengchongfu** [comment]
@gebilaoxiong , but all array in hand-written render function will not get a key, I don't know whether it is a good solution.

**Comment by gebilaoxiong** [comment]
@pengchongfu 

I think this happens only when there are nested arrays in children

just like:

```javascript
children: [
  [vnode, vnode...]
]
```

In the `render` of the template, it will be treated as `v-for`

but `slot` and` render function` will also generate this structure

so we just skip to set the key

**Comment by gebilaoxiong** [comment]
@pengchongfu wait, I have a better way to solve this problem！

**Comment by gebilaoxiong** [comment]
@pengchongfu 

I marked the `v-for` generated elements

Only v-for generated elements will be set to `key`

avoiding `render function` and` slot` to generate the same structure when an error occurs

**Comment by gebilaoxiong** [comment]
@yyx990803 

Well, it looks like I'm the last one waiting for today

Do not close my PR, tell me this is not the best way 😄

File: src/core/instance/render-helpers/render-list.js [hunk 2]
```diff
@@ -9,23 +9,29 @@ export function renderList (
...
     keys = Object.keys(val)
     ret = new Array(keys.length)
     for (i = 0, l = keys.length; i < l; i++) {
       key = keys[i]
-      ret[i] = render(val[key], key, i)
+      vnode = render(val[key], key, i)
+      vnode.isListItem = true
+      ret[i] = vnode
     }
   }
```
Comment (yyx990803) [inline src/core/instance/render-helpers/render-list.js]: Instead of adding a property to every vnode, we can simply mark the `ret` array here with something like:

``` js
if (isDef(ret)) {
  (ret: any)._isVList = true // work around flow
}
```

Then check `children._isVList` in `normalizeArrayChildren`.

Comment (gebilaoxiong) [inline src/core/instance/render-helpers/render-list.js]: Yes, I also feel that there are some problems, very grateful

**Comment by gebilaoxiong** [comment]
@yyx990803 

Fix bug is really a very interesting thing

Maybe my level is not enough, just think you need to chew and then get the truth

**Comment by yyx990803** [comment]
I pushed a commit to ensure `nestedIndex` is always passed down for nested arrays. This is necessary in cases where there are two `v-for` lists nested under non `v-for` arrays, e.g.

``` js
[[[v-for list], ..., [[v-for list]]]
```

**Comment by gebilaoxiong** [comment]
understand, thank you very much
