### PR TITLE
Fix when functional component render method retrun null (fix #5536)

### LINKED ISSUE #5536: [2.3.0] Uncaught TypeError: Cannot set property 'isRootInsert' of null
### Version
2.3.0

### Reproduction link
2.3.0 - [https://jsfiddle.net/f0n7jmL7/](https://jsfiddle.net/f0n7jmL7/)
2.2.6 - [https://jsfiddle.net/eu1q0a8b/](https://jsfiddle.net/eu1q0a8b/)

### Steps to reproduce
1. Open bug reproduction for 2.3.0 and check console.log - you ca see an error
2. Make change in FormErrors component so it will return empty `span` tag  instead of `null` value at the end - no error this time and the example works fine

### What is expected?
i expect the above example to work as it did in vue@2.2.6

### What is actually happening?
Vue throws an error `Uncaught TypeError: Cannot set property 'isRootInsert' of null` when functional component returns null value instead of vnode.

// EDIT: Also something I noticed in 2.3.0. If you will return `undefined` instead of `null` at the end of FormErrors, then our example works again.

### PR DESCRIPTION
**Pull request by gebilaoxiong**
issue: https://github.com/vuejs/vue/issues/5536

Originally I wanted to use `isDef` but the flow was a bit of a problem

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by gebilaoxiong** [comment]
wait a minute I add a test!

File: src/core/vdom/create-element.js [hunk 1]
```diff
@@ -99,7 +99,7 @@ export function _createElement (
     // direct component options / constructor
     vnode = createComponent(tag, data, context, children)
   }
-  if (vnode !== undefined) {
+  if (vnode !== undefined && vnode !== null) {
```
Comment (posva) [inline src/core/vdom/create-element.js]: you can do `vnode != null`

Comment (gebilaoxiong) [inline src/core/vdom/create-element.js]: yes  but the lint forced to use  `! ==`

Comment (posva) [inline src/core/vdom/create-element.js]: I mean `if (vnode != null)`

Comment (gebilaoxiong) [inline src/core/vdom/create-element.js]: thanks

Comment (yyx990803) [inline src/core/vdom/create-element.js]: Actually you can just use `isUndef(vnode)` here

**Comment by gebilaoxiong** [comment]
hold on, the test case is not very accurate

**Comment by gebilaoxiong** [comment]
it case by 
https://github.com/vuejs/vue/blob/dev/src/core/vdom/create-functional-component.js#L35

`functional component` render return null

ping @posva @yyx990803

File: src/core/vdom/create-element.js (hunk 1 above)
Comment (gebilaoxiong) [inline src/core/vdom/create-element.js]: flow has some problems

Comment (gebilaoxiong) [inline src/core/vdom/create-element.js]: @yyx990803 
if use `isUndef` like this:
```javascript
 if (isUndef(vnode)) {
    return createEmptyVNode()
  } else {
    if (ns) applyNS(vnode, ns)
    return vnode
  }
```
or use `isDef`

then run test:
```

> vue@2.3.0 test /Users/xiongyang/workspace/gebilaoxiong/vue
> npm run lint && flow check && npm run test:types && npm run test:cover && npm run test:e2e -- --env phantomjs && npm run test:ssr && npm run test:weex


> vue@2.3.0 lint /Users/xiongyang/workspace/gebilaoxiong/vue
> eslint src build test

src/core/vdom/create-element.js:106
106:     return vnode
                ^^^^^ undefined. This type is incompatible with the expected return type of
 51: ): VNode {
        ^^^^^ VNode

src/core/vdom/create-element.js:111
111:   vnode.ns = ns
             ^^ property `ns`. Property cannot be assigned on possibly undefined value
111:   vnode.ns = ns
       ^^^^^ undefined

src/core/vdom/create-element.js:112
112:   if (vnode.tag === 'foreignObject') {
                 ^^^ property `tag`. Property not found in possibly undefined value
112:   if (vnode.tag === 'foreignObject') {
           ^^^^^ undefined

src/core/vdom/create-element.js:116
116:   if (Array.isArray(vnode.children)) {
                               ^^^^^^^^ property `children`. Property not found in possibly undefined value
116:   if (Array.isArray(vnode.children)) {
                         ^^^^^ undefined


Found 4 errors
```

Comment (HerringtonDarkholme) [inline src/core/vdom/create-element.js]: Sadly, flow does not support custom type predicate function.  

https://github.com/facebook/flow/issues/34

One workaround is to annotate `function isDef(obj): %checks {}`, using internal type check.

**Comment by gebilaoxiong** [comment]
According to my years of closed experience, I feel like being closed again 😢

**Comment by HerringtonDarkholme** [comment]
Dear @gebilaoxiong amigo, your contribution is important for Vue's community. Keep going!

Personally I think this is a valid bug and needs to be fixed. So please be patient.

I also think the `isDef` flow problem can be fixed. I'm working on it.

**Comment by gebilaoxiong** [comment]
@HerringtonDarkholme 

Thanks for your reply, I just got a joke 😄

**Comment by HerringtonDarkholme** [comment]
Oh, this is closed automatically by GitHub. 

But I think this pull request needs some polish (use `isDef`) and then it can be ready.

File: src/core/vdom/create-element.js [hunk 2]
```diff
@@ -99,7 +99,7 @@ export function _createElement (
     // direct component options / constructor
     vnode = createComponent(tag, data, context, children)
   }
-  if (vnode !== undefined) {
+  if (vnode != null) {
```
Comment (HerringtonDarkholme) [inline src/core/vdom/create-element.js]: Now you can use isDef. Flow will pick it up.

**Comment by gebilaoxiong** [comment]
wow,lucky day!thank you everyone
