### PR TITLE
fix #8865: skip mixins and extends if child is already merged

### LINKED ISSUE #8865: Vue.extend causes nested mixins to be merged twice
### Version
2.5.17

### Reproduction link
[https://codepen.io/anon/pen/ReNVra?editors=0011](https://codepen.io/anon/pen/ReNVra?editors=0011)

### Steps to reproduce
Open the console

### What is expected?
```
"mixinA created"
"mixinB created"
"ChildComponent created"
```

### What is actually happening?
```
"mixinA created"
"mixinA created"
"mixinB created"
"ChildComponent created"
```

---
`MixinB.options` still has `mixins`, which gets applied again if used in `mixins: []` or `extends: ` even though `Vue.extend()` has already done that

### PR DESCRIPTION
**Pull request by KaelWD**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
fixes #8865

### CODE REVIEW

File: src/core/util/options.js [hunk 1]
```diff
@@ -379,10 +379,10 @@ export function mergeOptions (
   normalizeInject(child, vm)
   normalizeDirectives(child)
   const extendsFrom = child.extends
-  if (extendsFrom) {
+  if (extendsFrom && !child._base) {
```
Comment (KaelWD) [inline src/core/util/options.js]: Not sure if there's some other flag that's supposed to be used for this, but the presence of `_base` seemed like a decent indicator at a glance.
