### PR TITLE
fix($compiler): Allow using array value with array v-model in checkboxes, fix #6219

### LINKED ISSUE #6219: checkbox with array model doesn't work with an array value
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/0wvstw39/1/](https://jsfiddle.net/0wvstw39/1/)

### Steps to reproduce
1. Create `<input type="checkbox" :value="[1]" />`
2. Bind it to an array using `v-model`.

### What is expected?
Toggling the checkbox will add/remove the `value` array to the `v-model` array.

### What is actually happening?
Toggling the checkbox adds the contents of the `value` array to the `v-model` array. Checkbox is not toggled and contents are added as many times as clicked.

### PR DESCRIPTION
**Pull request by nickmessing**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
Fix #6219

### CODE REVIEW

File: src/platforms/web/compiler/directives/model.js [hunk 1]
```diff
@@ -93,7 +93,7 @@ function genCheckboxModel (
     'if(Array.isArray($$a)){' +
       `var $$v=${number ? '_n(' + valueBinding + ')' : valueBinding},` +
           '$$i=_i($$a,$$v);' +
-      `if($$el.checked){$$i<0&&(${value}=$$a.concat($$v))}` +
+      `if($$el.checked){$$i<0&&(${value}=$$a.concat(Array.isArray($$v)?[$$v]:$$v))}` +
```
Comment (nickmessing) [inline src/platforms/web/compiler/directives/model.js]: We could just use `[$$v]` instead of `Array.isArray($$v)?[$$v]:$$v` I guess :-S

Comment (posva) [inline src/platforms/web/compiler/directives/model.js]: I think using `[$$v]` is a safer way of doing it. No need for ternary imo
You can add a comment if you want

Comment (nickmessing) [inline src/platforms/web/compiler/directives/model.js]: @posva, you're right and it's common enough, doesn't need a comment.
