### PR TITLE
fix(core): Use native bind function instead of own (fix #7408)

### LINKED ISSUE #7408: Bind implementation is slower when native in modern browsers
### Version
2.5.13

### Reproduction link
[https://jsperf.com/vue-bind-perf](https://jsperf.com/vue-bind-perf)

### Steps to reproduce
Run tests across some modern browsers to see the result.

### What is expected?
Custom bind implementation performance is the same level as native.

### What is actually happening?
Custom bind implementation performance is lower than native.

---
Tested in:
* Safari - native is **slower 83%**
* Chrome - native is **faster 61%**
* Edge - native is **faster 91%**
* Firefox - native is **faster 52%**

I believe it is not an issue at all, but I think it is something which can be improved.

### PR DESCRIPTION
**Pull request by dmitry-vakhnenko**
Simple refactor bind function for easy revert.
Custom bind implementation performance is lower than native. ( https://jsperf.com/vue-bind-perf )

issue link: https://github.com/vuejs/vue/issues/7408

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by yyx990803** [comment]
Some browsers in the support range e.g. PhantomJS don't have `Function.prototype.bind`, so we should only use the native version when it exists.

**Comment by OEvgeny** [comment]
Maybe it's better to decide at first module run which implementation to use? e.g.:
```js
export const bind = Function.prototype.bind ? nativeBind : bind
```

**Comment by dmitry-vakhnenko** [comment]
> Maybe it's better to decide at first module run which implementation to use? e.g.:

```JavaScript
const ownBind = (fn: Function, ctx: Object) => {
  function boundFn(a) {
    const l = arguments.length
    return l
      ? l > 1
        ? fn.apply(ctx, arguments)
        : fn.call(ctx, a)
      : fn.call(ctx)
  }

  boundFn._length = fn.length
  return boundFn
}

export const bind = Function.prototype.bind ? Function.prototype.bind : ownBind
```

**Comment by dmitry-vakhnenko** [comment]
> Some browsers in the support range e.g. PhantomJS don't have Function.prototype.bind, so we should only use the native version when it exists.

Why we should carry polyfill for this? Phantomjs is a `virtual` browser that can be used for `tests` and scrapping. We carry polyfill for case when any vuejs site can be scrapped?

We increase bundle size for every build for ^ case?

I just didn't understood.

**Comment by OEvgeny** [comment]
I think
> ```js
> ...
> export const bind = Function.prototype.bind ? Function.prototype.bind : ownBind
> ```

Should be:
```js
function ownBind(fn: function, ctx: object) {
  // internal/current implementation ...
}

function nativeBind(fn: function, ctx: object) {
  return fn.bind(ctx)
}

export const bind = Function.prototype.bind ? nativeBind : ownBind
```

Because of how native `bind` should be called.

**Comment by dmitry-vakhnenko** [comment]
So maybe wrap polyfill version in `if (process.NODE_ENV == 'development')` ? its removes dead code  in production builds and broke dead some e2e tests and scrappers.

I don't see its as as breaking change.

**Comment by yyx990803** [comment]
**It is a breaking change if you remove a polyfill.**

Someone's tests that were able to run in PhantomJS would break suddenly in a patch release because of that.

**Comment by dmitry-vakhnenko** [comment]
> It is a breaking change if you remove a polyfill.

Then its ready for PR.

**Comment by yyx990803** [comment]
I think @OEvgeny 's suggestion should be applied so that we only check native bind once on initialization.

File: src/shared/util.js [hunk 1]
```diff
@@ -174,22 +174,28 @@ export const hyphenate = cached((str: string): string => {
...
       : fn.call(ctx)
   }
-  // record original fn length
+
   boundFn._length = fn.length
   return boundFn
 }
 
+function nativeBind(fn: Function, ctx: Object): Function {
+  return fn.bind(ctx)
```
Comment (dsonet) [inline src/shared/util.js]: It's missing the optional arguments, cause different behavior to ownBind

Comment (OEvgeny) [reply src/shared/util.js]: I see no optional arguments in `ownBind`. Are you about `fn._length`? If yes. It shouldn't be a problem because we should check both `length` and `_length` since we don't know exactly was the `fn` bound via our `ownBind` or not. e.g.: https://github.com/vuejs/vue/blob/7cf188e134fe7bfc9e8a16b763fb85b18eff1eac/src/platforms/weex/runtime/modules/transition.js#L73

**Comment by rlightner** [comment]
I think this broke something. if fn.bind is undefined it blows up.

**Comment by yyx990803** [comment]
@rlightner please provide a reproduction. `fn.bind` is only used when `Function.prototype.bind` exists. `fn.bind` cannot be undefined in that case unless `fn` is not a function.

**Comment by rlightner** [comment]
I'll try. The fn being passed in is a method in a template that contains:

```
drawer: {
    get() {
        return this.$store.state.drawer
    }
    , set(value) {
        this.$store.commit('toggleDrawer', value)
    }
}
```
and it's being passed in to `nativeBind` as the get/set. That doesn't have a bind(). This is in a normal vue template.

image

**Comment by rjoo** [comment]
As @rlightner pointed out, this exposed a coding error if whatever's provided to the `bind` helper is not a function.

Version 2.5.13 https://jsfiddle.net/ujxu9mvd/ Renders fine, fails silently
Version 2.5.14 https://jsfiddle.net/bad4a8mb/1/ Does NOT render and it throws an Uncaught TypeError
