### PR TITLE
fix #8842: Override v-bind object with kebab-cased props

### LINKED ISSUE #8842: Overriding a binded prop with hypenated syntax instead of camelCase not working
### Version
2.5.17

### Reproduction link
[https://codesandbox.io/s/1zr10x8rpq](https://codesandbox.io/s/1zr10x8rpq)

### Steps to reproduce
- Create two child components with the same prop in camelCase
- Bind props from first child to second
- Try to override camelCase prop in hypenated syntax from first child to second

### What is expected?
Prop override correctly

### What is actually happening?
Prop keep parent value

---

Meet this issue because I have a camelCase coding stye. But eslint vue-recommended throw an error on if prop is not hypenated.

### PR DESCRIPTION
**Pull request by Justineo**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

File: src/core/instance/render-helpers/bind-object-props.js [hunk 1]
```diff
@@ -43,12 +44,13 @@ export function bindObjectProps (
...
         }
-        if (!(key in hash)) {
+        const camelizedKey = camelize(key)
+        if (!(key in hash) && !(camelizedKey in hash)) {
           hash[key] = value[key]
 
           if (isSync) {
             const on = data.on || (data.on = {})
-            on[`update:${key}`] = function ($event) {
+            on[`update:${camelizedKey}`] = function ($event) {
```
Comment (Justineo) [inline src/core/instance/render-helpers/bind-object-props.js]: This change will become unnecessary once #8297 is merged. But let's keep it for now.
