### PR TITLE
fix #6931: Clean up target variables to avoid memory leaks

### LINKED ISSUE #6931: Memory leak in updateDOMListeners and updateComponentListeners
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/opzzsudp/](https://jsfiddle.net/opzzsudp/)

### Steps to reproduce
1. Create a Vue instance that has a reference to a large object in its data
1. Render either a component or an element with any event handler
1. Destroy the Vue instance, remove its element, null out its reference

### What is expected?
The Vue instance and the references it contains should be freed for garbage collection

### What is actually happening?
The `target` variables [here](https://github.com/vuejs/vue/blob/dev/src/platforms/web/runtime/modules/events.js#L29) or [here](https://github.com/vuejs/vue/blob/dev/src/core/instance/events.js#L22) hang onto references and prevent garbage collection

---
I have a fix ready for this and will be filing a PR shortly

### PR DESCRIPTION
**Pull request by fenduru**
**What kind of change does this PR introduce?** (check at least one)

- [X] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [X] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [X] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [X] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [X] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
The development environment on Windows is flaky and crashes a lot. I'm also seeing intermittent failures that seem unrelated to my change (they also occur on the `dev` branch with no changes). Filing the PR now to get feedback and to see if CI has the same failures.

### CODE REVIEW

File: src/core/instance/events.js [hunk 1]
```diff
@@ -19,7 +19,7 @@ export function initEvents (vm: Component) {
   }
 }
 
-let target: Component
+let target: any
```
Comment (fenduru) [inline src/core/instance/events.js]: I don't love removing the type annotation here, but if I left it as `Component` then Flow would see the assignment to undefined and error due to "Possible undefined value".

In typescript you can tell the type checker to trust you by doing `target!.method()` but I couldn't find an equivilent in Flow. The Flow docs recommend `if (target !== undefined)`, however I didn't think we'd want to add a branch in the VDom code.

Comment (chriscasola) [reply src/core/instance/events.js]: What about just binding the `add` and `remove` methods to the `vm` so you don't need this closure variable at all?

Comment (dsonet) [reply src/core/instance/events.js]: @chriscasola You won't wanna do it that way. function.bind is just create a closure.
