### PR TITLE
fix(#8567): handle errors on immediate watchers

### LINKED ISSUE #8567: Immediate watcher skips parent(s) errorCaptured and jumps straight to the top error handler
### Version
2.5.16

### Reproduction link
[https://codesandbox.io/s/wkpy6x5r25](https://codesandbox.io/s/wkpy6x5r25)

### Steps to reproduce
Simply opening and running the sandbox should show the error. Instead of getting an alert that App.vue caught the error in HelloWorld's watcher, the error escapes all the way to the top level. To see the expected behavior, open Hello World and set the watcher to immediate: false. Then hit the button to trigger the watcher. In this case the error is caught by the parent, App.vue. In the immediate case, this does not happen.

### What is expected?
Errors in immediate watchers should be caught by the parent component(s)'s errorCaptured().

### What is actually happening?
The error escapes to the nextTick hander. This handler has no ctx or vm to pass to the errorHandler. When errorHandler does not receive a vm, it cannot call the parent errorCaptured handlers.

---
This appears to be an oversight in src/core/instance/state.js. In the case options.immediate is true, cb.call(vm, watcher.value) should be wrapped in a try catch that explicitly calls handleError with the vm.

A proposed fix:
```
    if (options.immediate) {
      try {
        cb.call(vm, watcher.value)
      } catch (e) {
        handleError(e, vm, `immediate call for watcher ${watcher.expression}`)
      }
    }
```

### PR DESCRIPTION
**Pull request by afontcu**
As stated in the [related issue](https://github.com/vuejs/vue/issues/8567), the handle callback call should be wrapped in a try/catch that explicitly calls handleError.

fix #8567

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
This is my first PR so feel free to provide feedback or request modifications both in the code and the PR itself! 😄

### CODE REVIEW

File: src/core/instance/state.js [hunk 1]
```diff
@@ -346,7 +346,11 @@ export function stateMixin (Vue: Class<Component>) {
     options.user = true
     const watcher = new Watcher(vm, expOrFn, cb, options)
     if (options.immediate) {
-      cb.call(vm, watcher.value)
+      try {
```
Comment (posva) [inline src/core/instance/state.js]: Should we call `watcher.getAndInvoke` @yyx990803 ?
