### PR TITLE
fix(ssr): fix nested async functional componet rendering

### LINKED ISSUE #9643: Resolving nested async functional components is broken
### Version
2.6.8

### Reproduction link
[https://codesandbox.io/s/l07lp5vom](https://codesandbox.io/s/l07lp5vom)

### Steps to reproduce
As already quickly mentioned in here https://github.com/vuejs/vue/commit/03c13de38e883636917800a283ebcb338bbfbdc3 nested functional components are broken since 2.6.8
1.) I have 2 functional components in the repro (`Logo.vue` / `LogoWrapper.vue`)
2.) The components are registered globally as async components (doesn't really make sense in this case.. but you should get the point :-)). Check `components/_globals.js`
3.) Using one of the component in the other (Logo inside LogoWrapper) breaks with the errormessage "Cannot read property '$on' of null" - this was working prior to 2.6.8

### What is expected?
Components are renderer, no error message.

### What is actually happening?
TypeError
Cannot read property '$on' of null

### PR DESCRIPTION
**Pull request by dejour**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
fix #9643

### CODE REVIEW

File: src/core/vdom/helpers/resolve-async-component.js [hunk 1]
```diff
@@ -53,7 +53,7 @@ export function resolveAsyncComponent (
   }
 
   const owner = currentRenderingInstance
-  if (isDef(factory.owners) && factory.owners.indexOf(owner) === -1) {
+  if (isDef(factory.owners) && factory.owners.indexOf(owner) === -1 && owner) {
```
Comment (dsonet) [inline src/core/vdom/helpers/resolve-async-component.js]: If so, I think should put owner ahead.

File: src/core/vdom/helpers/resolve-async-component.js [hunk 2]
```diff
@@ -62,7 +62,7 @@ export function resolveAsyncComponent (
     return factory.loadingComp
   }
 
-  if (!isDef(factory.owners)) {
+  if (!isDef(factory.owners) && owner) {
```
Comment (dsonet) [inline src/core/vdom/helpers/resolve-async-component.js]: The same as here
