### PR TITLE
fix(vdom): avoid executing root level script tags

### LINKED ISSUE #11483: Root level script tag should not be executed
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/cranky-moser-p90di?file=/src/main.js](https://codesandbox.io/s/cranky-moser-p90di?file=/src/main.js)

### Steps to reproduce
Put valid <script> element in template string

### What is expected?
Script should be blocked from executing

### What is actually happening?
Script executes

---
As the example illustrates, if a <script> element is the sole element passed into the template string of a component, it will execute said script block. However if it's pre-ceded by a valid element, eg: a div the script is blocked from execution by the renderer. You do not have to close said element as shown in examples, simply preceding the script tag with a valid opening tag suffices. I believe this is because the renderer automatically closes elements with missing closures.

### PR DESCRIPTION
**Pull request by shadowings-zy**
**What kind of change does this PR introduce?** (check at least one)

- [ x ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ x ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ x ] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ x ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ x ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ x ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
Root level <script> tags should not be executed, for consistent behavior. So I remove the code in <script> tag when the <script> tag is the root element of the template.

fix #11483

### CODE REVIEW

**Comment by shadowings-zy** [comment]
Aha, I've thought about fix this bug at the compilation level！
But when I read the code I found that if a render function that returns null, the template will render a <div> as a default element (related codes in file 'src/compiler/codegen/index.js', in 'generate' function). Does this meet our expectations?

If so, I will work on it.

**Comment by posva** [comment]
if the render function returns null, Vue will output a comment node. But still, it is better that way, yes

**Comment by shadowings-zy** [comment]
Hi, now I fix this bug at the compilation level.
and `Vue.compile('<script` />')` will creates a render function that returns null.

The output of the render function is as follows:

```
function anonymous(
) {
with(this){return null}
}
```

: )

File: src/compiler/codegen/index.js [hunk 1]
```diff
@@ -45,7 +45,7 @@ export function generate (
   options: CompilerOptions
 ): CodegenResult {
   const state = new CodegenState(options)
-  const code = ast ? genElement(ast, state) : '_c("div")'
+  const code = ast ? (ast.tag === 'script' ? 'null' : genElement(ast, state) ) : '_c("div")'
```
Comment (posva) [inline src/compiler/codegen/index.js:48]: can you add a comment above referencing the original issue?

Comment (shadowings-zy) [reply src/compiler/codegen/index.js:48]: ok, I will add the issue

**Comment by shadowings-zy** [comment]
I had added a comment referencing the original issue in the PR.

: )
