### PR TITLE
fix #6193, change event should not be triggered if each value still matches an option

### LINKED ISSUE #6193: Select with v-model triggers change event when its options are changed
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/floorish/e2h2vwc2/](https://jsfiddle.net/floorish/e2h2vwc2/)

### Steps to reproduce
Dynamically change the `<option>`s in a `<select v-model="val">` tag and the `v-model` triggers a change event, but the actually chosen option hasn't changed.

### What is expected?
`v-model` does not trigger a change event

### What is actually happening?
`v-model` triggers a change event

---
Change of behaviour intruduced in https://github.com/vuejs/vue/commit/c90b140e80f1bd5d01c733a5bd9fa6e9cb3c2b4d

### PR DESCRIPTION
**Pull request by jkzing**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
[https://github.com/vuejs/vue/issues/6193](https://github.com/vuejs/vue/issues/6193)

---
It seems we still need the value matching check, only detect options change is not enough.

### CODE REVIEW

File: src/platforms/web/runtime/directives/model.js [hunk 1]
```diff
@@ -101,6 +108,15 @@ function setSelected (el, binding, vm) {
   }
 }
 
+function hasNoMatchingOption (value, options) {
```
Comment (Kingwl) [inline src/platforms/web/runtime/directives/model.js]: how about Array.prototype.some😅

Comment (jkzing) [inline src/platforms/web/runtime/directives/model.js]: Yes, it would be better to use [].some. 
Actually I just did revert changes made in [https://github.com/vuejs/vue/commit/c90b140e80f1bd5d01c733a5bd9fa6e9cb3c2b4d](https://github.com/vuejs/vue/commit/c90b140e80f1bd5d01c733a5bd9fa6e9cb3c2b4d), and didn't think about it. 😅
Will do it later.

**Comment by cgarnier** [comment]
Is it released ?

**Comment by LinusBorg** [comment]
It hasn't been merged yet, so: no.
