### PR TITLE
fix #9571, rendering async components after initial context was destroyed

### LINKED ISSUE #9571: Components created with async component factory break on route change
### Version
2.6.7

### Reproduction link
[https://codesandbox.io/s/239l9qnkxn](https://codesandbox.io/s/239l9qnkxn)

### Steps to reproduce
1. Open https://codesandbox.io/s/239l9qnkxn
2. Immediately (before the async component is resolved within 7 sec) click on the "Some Page" link
3. Click on the "Home" link (before 7s are elapsed)

### What is expected?
The AsyncReady component should render after 7 seconds.

### What is actually happening?
The AsyncLoading component is shown forever

---
The problem is that the `currentRenderingInstance` is `Home`. After rendering the `SomePage` route, the initial `Home` instance (which is stored as the `owner` of the factory) is destroyed. As soon as the factory calls `forceRender`, triggering `$forceUpdate()` on the owner does nothing because the old `Home` instance already was destroyed and a new one was created when navigating back to `Home`.

This is problematic on very slow connections when users click a link before all dynamic components were resolved or in case of automatic redirects which are triggered immediately after a page is loaded (after checking auth for example).

See: https://github.com/vuejs/vue/blob/dev/src/core/vdom/helpers/resolve-async-component.js#L58-L74

### PR DESCRIPTION
**Pull request by maoberlehner**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No
- [ ] Maybe (I'm not sure)

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

I have not heavily tested this in a lot of circumstances. The async part of it almost broke my brain ^^ But tests are passing, so... ¯\_(ツ)_/¯

### CODE REVIEW

File: src/core/vdom/helpers/resolve-async-component.js [hunk 1]
```diff
@@ -51,18 +51,27 @@ export function resolveAsyncComponent (
...
     const owners = factory.owners = [owner]
     let sync = true
 
+    const removeOwner = (destroyedOwner) => {
+      const index = owners.indexOf(destroyedOwner)
+      if (index > -1) owners.splice(index, 1)
+    }
+
+    if (owner) owner.$on('hook:destroyed', () => removeOwner(owner))
+
```
Comment (maoberlehner) [inline src/core/vdom/helpers/resolve-async-component.js]: This stuff isn't mandatory. It doesn't break anything if destroyed owners are fore updated. But it might be cleaner to remove them.

File: src/core/vdom/helpers/resolve-async-component.js [hunk 2]
```diff
@@ -51,18 +51,27 @@ export function resolveAsyncComponent (
...
   if (isTrue(factory.loading) && isDef(factory.loadingComp)) {
     return factory.loadingComp
   }
 
-  const owner = currentRenderingInstance
-  if (isDef(factory.owners)) {
-    // already pending
-    factory.owners.push(owner)
-  } else {
+  if (!isDef(factory.owners)) {
```
Comment (maoberlehner) [inline src/core/vdom/helpers/resolve-async-component.js]: Not too happy with double checking for `isDef(factory.owners)` here and above but cleaner than moving this block above the block which returns the `loadingComp` I guess?!
