### PR TITLE
Fixed #2988

### LINKED ISSUE #2988: [BUG] one time binding doesn't deal with null like value properly
### Vue.js version
1.0.24

### Reproduction Link
http://jsbin.com/yesozewezu/1/edit?html,js,output

### Steps to reproduce
For one time binding, undefined value would display as "undefined", it's different from two-way binding.
### What is Expected?
Should display as empty.
### What is actually happening?
Display undefined.

### PR DESCRIPTION
**Pull request by dsonet**
Make rendering of undefined and null in one-time binding mode as same as reactive binding.

### CODE REVIEW

**Comment by LinusBorg** [comment]
Hello dsonet, 

Thank you very much for your bug report and this pull request with a suggested fix. 

We will review it and come back to you shortly..

File: src/compiler/compile.js [hunk 1]
```diff
@@ -446,7 +446,7 @@ function makeTextNodeLinkFn (tokens, frag) {
           if (token.html) {
             replace(node, parseTemplate(value, true))
           } else {
-            node.data = value
+            node.data = value === undefined ? '' : value
```
Comment (yyx990803) [inline src/compiler/compile.js]: Let's use [this function](https://github.com/vuejs/vue/blob/dev/src/util/lang.js#L114) for consistency with normal bindings.

Comment (dsonet) [inline src/compiler/compile.js]: Sure.
