### PR TITLE
fix #6209, selected option not updated properly under IE11

### LINKED ISSUE #6209: select element can't be rendered correctly by vue 2.0.0 (or above) in IE 11
### Version
2.4.2

### Reproduction link
[https://jsfiddle.net/ntdd9g2a/86/](https://jsfiddle.net/ntdd9g2a/86/)

### Steps to reproduce
1. open the link in IE11
2. see the select element does't be rendered correctly

### What is expected?
The second option('菜单二') in select element should be in view 

### What is actually happening?
The third option('菜单三') in select element is still in view 

---
I have to use setTimeout to solve this problem. So i want to know how it happened

### PR DESCRIPTION
**Pull request by jkzing**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

[https://github.com/vuejs/vue/issues/6209#issuecomment-317715265](https://github.com/vuejs/vue/issues/6209#issuecomment-317715265)

### CODE REVIEW

File: src/platforms/web/runtime/directives/model.js [hunk 1]
```diff
@@ -67,37 +60,45 @@ export default {
...
+      el.selectedIndex = -1
+    }
   }
-  if (!isMultiple) {
-    el.selectedIndex = -1
+
+  cb()
+  /* istanbul ignore if */
+  if (isIE || isEdge) {
+    setTimeout(cb, 0)
```
Comment (nickmessing) [inline src/platforms/web/runtime/directives/model.js]: :heart: javascript, this code reminds me of good old angular rule, if it doesn't work - `$timeout` it :joy:

Comment (nesterone) [reply src/platforms/web/runtime/directives/model.js]: What else you can suppose from `isIE || isEdge` ? ;-)
