### PR TITLE
fix(compiler): Allow BigInt usage in templates

### LINKED ISSUE #11126: Allow BigInt usage in templates
### What problem does this feature solve?
It would allow us to use numbers which is larger than MAX_SAFE_INTEGER. 

### What does the proposed API look like?
In HTML, `{{BigInt("100")}}`, `{{100n}}`, `{{2n * 50n}}` or `{{50n + 50n}}` should show "100" (it can be just simply string by using .toString()) at frontend.
At the moment using BigInt in "Mustache" syntax just throw error.
Sure, backup solution would be using external functions or converted into string and save it to variable. But using BigInt directly in HTML would be nice to have.
More Information about BigInt -> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

### PR DESCRIPTION
**Pull request by shadowings-zy**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ x ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ x ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ x ] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ x ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ x ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ x ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ x ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
Hello!
This pull request is related to issue #11126 . Now we can use BigInt in "Mustache" syntax.
I had already added test for this feature in "test/unit/features/filter/filter.spec.js".
And all tests are passing.

Close #11126

### CODE REVIEW

**Comment by posva** [comment]
Hi, thanks for the PR but this is not what was mentioned on the issue. The idea is to allow the use of BigInt when it's available and fail if it's not. See https://jsfiddle.net/syrnaefq/. This should work on browsers supporting `BigInt`. It's similar to allowing `Number` in templates. The syntax `100n` seems to already work when it's supported by the browser.
The goal is not to polyfill the feature

**Comment by shadowings-zy** [comment]
That makes me a little confused...
In my pull request," {{ BigInt(100) }}" and "{{ 100n }}" both work when BigInt is available, and fail if it is not ( and warn 'BigInt is not support! ' )

It seems that the idea of this issue is the same to my PR🤦‍♂️？

**Comment by shadowings-zy** [comment]
Did you mean: 'We need to "{{ BigInt(100) }}" and "{{ 100n }}" both work when BigInt is available, and fail if it is not' like ' "{{ Number(100) }}" and "{{ 100n }}" both work'?

If so, I get your point and I will fix it in this way.

**Comment by shadowings-zy** [comment]
Hi @posva !
I revert the previous commits and I rewrite the code to allow BigInt usage in templates.
As you see it just like allow `Number` in template.

截屏2020-02-2721 47 18

If it's OK, please merge this PR, if not, let's discuss further : )

File: src/core/instance/proxy.js [hunk 1]
```diff
@@ -6,11 +6,16 @@ import { warn, makeMap, isNative } from '../util/index'
...
+    (typeof window !== 'undefined' && typeof window.BigInt === 'function') ||
+    (typeof global !== 'undefined' && typeof global.BigInt === 'function')
+
   const allowedGlobals = makeMap(
     'Infinity,undefined,NaN,isFinite,isNaN,' +
     'parseFloat,parseInt,decodeURI,decodeURIComponent,encodeURI,encodeURIComponent,' +
     'Math,Number,Date,Array,Object,Boolean,String,RegExp,Map,Set,JSON,Intl,' +
-    'require' // for Webpack/Browserify
+    'require,' + // for Webpack/Browserify
+    (supportBigInt ? 'BigInt' : '') // for BigInt support issue #11126
```
Comment (posva) [inline src/core/instance/proxy.js]: I think it's fine to not use a conditional, the same way we allow `Intl` even though it's not supported before IE 11

Comment (shadowings-zy) [reply src/core/instance/proxy.js]: OK，That sounds right，and I will add `BigInt` directly in makeMap()
: )

File: src/core/instance/proxy.js [hunk 2]
```diff
@@ -10,7 +10,8 @@ if (process.env.NODE_ENV !== 'production') {
     'Infinity,undefined,NaN,isFinite,isNaN,' +
     'parseFloat,parseInt,decodeURI,decodeURIComponent,encodeURI,encodeURIComponent,' +
     'Math,Number,Date,Array,Object,Boolean,String,RegExp,Map,Set,JSON,Intl,' +
-    'require' // for Webpack/Browserify
+    'require,' + // for Webpack/Browserify
+    'BigInt' // for BigInt support issue #11126
```
Comment (posva) [inline src/core/instance/proxy.js]: let's put it up after the Intl, the comment is not really necessary

Comment (shadowings-zy) [reply src/core/instance/proxy.js]: OK~, I fixed it in commit#4241f12

**Review by posva — CHANGES_REQUESTED** [review]
@shadowings-zy can you undo the merge you did? it seems to have messed up the PR

**Comment by shadowings-zy** [comment]
> @shadowings-zy can you undo the merge you did? it seems to have messed up the PR

@posva Sorry, I forgot I use `dev` branch to open this PR, and now I undo my merge.

**Review by posva — APPROVED** [review]
