### PR TITLE
fix(types):fix Spreading data functional components TSX type error (fix #12778)

### LINKED ISSUE #12778: Spreading data functional components TSX type error
### Version
2.7.10

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/heuristic-worker-fmt6wf?file=/src/components/A.tsx)

### Steps to reproduce
Spread `data` onto TSX component / intrinsic element causes type errors due to miss matching `style` definition of `VNodeData` property. 

https://github.com/vuejs/jsx-vue2#attributesprops

### What is expected?
Expect the spreading of `data` to not throw type error. 

### What is actually happening?
The style attribute expects the shape of `string | CSSProperties` however the `VNodeData` definition is `string | object[] | object`

### PR DESCRIPTION
**Pull request by k-furusho**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by k-furusho** [comment]
fix #12778

File: types/test/vue-test.ts [hunk 1]
```diff
@@ -42,7 +42,7 @@ class Test extends Vue {
     this.$delete({}, 'key')
     this.$watch('a', (val: number, oldVal: number) => {}, {
       immediate: true,
-      deep: false
+      deep: false,
```
Comment (yyx990803) [inline types/test/vue-test.ts:45]: Please remove these unrelated style changes

**Review by yyx990803 — CHANGES_REQUESTED** [review]
