### PR TITLE
fix: the first LF following pre and textarea tag should be ignored, fix #5992

### LINKED ISSUE #5992: ssr unexpected hydration bailout with <pre> tag
### Version
2.3.4

### Reproduction
Here what happens on F5 (reload) key:
ssr_pre_tag_issue
(It happens only once, the video is looped)

### Steps to reproduce
Add a `<pre>` tag in App.vue of the vue-hackernews-2.0 demo:

```
<template>
  <div id="app">
    <header class="header">
    <pre style="background-color: #aaa">
foobar
    </pre>
      <nav class="inner">

```

### What is expected?
client-side and server-side have the same version for the `<pre>` tag

### What is actually happening?
client and server side versions are not the same, then bailout ?, then `<pre>` tag content is flickering

### PR DESCRIPTION
**Pull request by defcc**
**What kind of change does this PR introduce?** (check at least one)

- [X] Bugfix
- [ ] Feature
- [X] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [X] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [X] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [X] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
fix #5992

### CODE REVIEW

File: src/compiler/parser/html-parser.js [hunk 1]
```diff
@@ -59,6 +59,10 @@ const decodingMap = {
 const encodedAttr = /&(?:lt|gt|quot|amp);/g
 const encodedAttrWithNewLines = /&(?:lt|gt|quot|amp|#10);/g
 
+// #5992
+const ignoreFirstLFTagList = makeMap('pre,textarea', true)
+const isIgnoreFirstLf = (tag, html) => tag && ignoreFirstLFTagList(tag.toLowerCase()) && html[0] === '\n'
```
Comment (javoski) [inline src/compiler/parser/html-parser.js]: Not need to call `toLowerCase()` here, and it seems `<textarea>` will never get into this function since `isPlainTextElement('textarea')` equals `true`.

Comment (defcc) [inline src/compiler/parser/html-parser.js]: 1. html5 tag names are case-insensitiv, so we use lower case to compare
2. isIgnoreFirstLf will be invoked when in textarea parse https://github.com/vuejs/vue/pull/6022/files#diff-084898b8c9f6d4d2833b18312180ef8fR172

Comment (javoski) [inline src/compiler/parser/html-parser.js]: 1. It'll call `toLowerCase()` when passing true to `makeMap` as the second param.
2. I didn't notice those changes starting from line 172, my fault😂.

Comment (defcc) [inline src/compiler/parser/html-parser.js]: 👍  Thanks, I missed it, I'll update.

Comment (defcc) [inline src/compiler/parser/html-parser.js]: Done.

**Comment by defcc** [comment]
The naming is much better, thanks :laughing:
