### PR TITLE
Static type="checkbox" with v-bind (fix #7811)

### LINKED ISSUE #7811: v-bind=$attrs overrides the input type attribute in 2.5.14 and above
### Version
2.5.14

### Reproduction link
[https://jsfiddle.net/linnea/onw3Lfm4/2/](https://jsfiddle.net/linnea/onw3Lfm4/2/)

### Steps to reproduce
Create a custom component with an input wrapped in a div and:

1. inherit attributes 
`v-bind="$attrs"`
2. Set the type attribute on the input
`type="checkbox"` 
3. Have a v-model on that input.

### What is expected?
The inner input still receives type="checkbox"

### What is actually happening?
No type attribute is inherited

---
We have a custom checkbox component that provides label styling etc, and used to be able to declare the input type as well as inherit attributes from the component. Other attributes that are set on the inner input are passed correctly (ie disabled, :true-value, etc), but not the type attribute, unless you bind it. This was working prior to v2.5.14.

A temporary fix we've implemented is changing `type="checkbox"` to `:type="'checkbox'"`, or setting v-bind="$attrs" to a computed property that returns an object with Object.assign({ type: 'checkbox'}, this.$attrs);

Removing the v-model from the input also fixes it, but we use it to handle multiple checkboxes, bound to the same array

Here's the same fiddle above, working in 2.5.13
https://jsfiddle.net/linnea/onw3Lfm4/4/

### PR DESCRIPTION
**Pull request by hirokiosame**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

File: src/platforms/web/compiler/modules/model.js [hunk 1]
```diff
@@ -34,7 +34,7 @@ function preTransformNode (el: ASTElement, options: CompilerOptions) {
     if (map[':type'] || map['v-bind:type']) {
       typeBinding = getBindingAttr(el, 'type')
     }
-    if (!typeBinding && map['v-bind']) {
+    if (!map.type && !typeBinding && map['v-bind']) {
```
Comment (jkzing) [inline src/platforms/web/compiler/modules/model.js]: This would make following case lose type binding: 
``` vue
<input type="checkbox" v-model="test" v-bind="{type: typeBindingValue}">
```

So maybe
```js
typeBinding = `(${map['v-bind']}).type || '${map.type}'`
```

Comment (posva) [reply src/platforms/web/compiler/modules/model.js]: @hirokiosame If you could add the test as well, that would be great 👌

Comment (yyx990803) [reply src/platforms/web/compiler/modules/model.js]: I don't think we should allow `v-bind` to override a static `type`, it's gonna be confusing if done accidentally and I don't think there's a valid use case.
