### PR TITLE
fix(provide): Merges symbol provides

### LINKED ISSUE #7923: Mixin provide with Symbols don't get merged properly
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/hirokiosame/38nzxq6c/26/](https://jsfiddle.net/hirokiosame/38nzxq6c/26/)

### Steps to reproduce
Run the code. The injected result will show `[undefined, "bar"]` in the console.

### What is expected?
For the merging to work properly. The expected result is `['foo', 'bar']`, which is what you'll see when you convert `keyA` and `keyB` into strings.

### What is actually happening?
Merging fails:  `[undefined, "bar"]`

### PR DESCRIPTION
**Pull request by hirokiosame**
Fixes merging multiple provides using Symbols

fix #7923

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
The test I added only passes in an environment with symbols (since it's handling a case that fails with symbols). This fails when the test is executed with Phantom, since it doesn't have Symbol support natively or with a polyfill, but passes in Chrome.

I can add babel-polyfill but seemed excessive for one test. Wanted to know how to move forward with that one before making any drastic changes to making it work.

### CODE REVIEW

File: src/core/util/options.js [hunk 1]
```diff
@@ -48,7 +49,14 @@ if (process.env.NODE_ENV !== 'production') {
 function mergeData (to: Object, from: ?Object): Object {
   if (!from) return to
   let key, toVal, fromVal
-  const keys = Object.keys(from)
+
+  const keys = hasSymbol
+    ? Reflect.ownKeys(from).filter(key => {
+      /* istanbul ignore next */
```
Comment (hirokiosame) [inline src/core/util/options.js]: Wasn't entirely sure if this was needed but took it from `inject.js` to be safe.

**Comment by posva** [comment]
Thanks for the contribution and sorry for the delay! I moved the test so it isn't run if `Reflect` isn't supported

**Comment by yyx990803** [comment]
Note: `Reflect.ownKeys` + filter with descriptor check is about 10x slower than `Object.keys()`, I think we need to avoid this cost for normal data merging, and only do this for `provide()` merges.
