### PR TITLE
fix(core): fix defineReactive unnecessary getters call fix #7280

### LINKED ISSUE #7280: Data getters are being invoked on component initialisation
### Version
2.5.11

### Reproduction link
[https://jsfiddle.net/7gmh5wL8/1/](https://jsfiddle.net/7gmh5wL8/1/)

### Steps to reproduce
* Run JSFiddle snippet 
* Open browser console
* You'll see a warning from property getter

### What is expected?
I expect, that my data and props enumerable properties will not be invoked, without my explicit call for them. 

### What is actually happening?
Seems, that `defineReactive` function in `/src/core/observer/index.js` works that way, that it accepts an object property value, instead of getting it from the getter on demand. Despite the fact, that it uses `getOwnPropertyDescriptor` to respect user-defined getters and setters. 

---
I faced this problem in a context of lazy-loaded backend entities. I have some redux store selectors, that returns RESTfull models. Some of the models nested properties are wrapped into getters, so I can call them, if needed and trigger a background api request for additional info. Now, all of the getters are invoked immediately and a bunch of requests is sent after initial rendering.

I can do a pull request, to fix this, but may be I do not understand some concept under this behaviour. 

Sorry for bad english.

### PR DESCRIPTION
**Pull request by DeyLak**
The defineReactive gets the property of the object, only if it has no getter

fix #7280

**What kind of change does this PR introduce?** (check at least one)

- [X] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [X] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [X] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [X] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [X] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [X] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

File: src/core/observer/index.js [hunk 1]
```diff
@@ -145,6 +145,9 @@ export function defineReactive (
 
   // cater for pre-defined getter/setters
   const getter = property && property.get
+  if (!getter && arguments.length <= 2) {
```
Comment (dsonet) [inline src/core/observer/index.js]: If so, it's better to be `arguments.length === 2`.
